- hosts: 'localhost'
  connection: local
  gather_facts: no
  # vars:
  #   jdks: "{{ lookup('file', './jdk8.json') | from_json }}"
  tasks:

    - name: Set fact
      set_fact:
        jdks: "{{ lookup('file', './jdk8.json') | from_json }}"

    # - name: Show the flat
    #   debug: var=jdks|flatten
      
    - name: Show the names
      include_tasks: adoptopenjdk_artifact.yml
      loop: "{{ jdks }}"
      loop_control:
        loop_var: release

  